"""bot_configs

Revision ID: a5b4b70ac7ba
Revises: d8aaff8c94ce
Create Date: 2026-01-10 17:49:21.477435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5b4b70ac7ba"
down_revision: Union[str, None] = "d8aaff8c94ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["customers.id"],
            name=op.f("fk__bot_configs__owner_id__customers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__bot_configs")),
        sa.UniqueConstraint("owner_id", name=op.f("uq__bot_configs__owner_id")),
        sa.UniqueConstraint("token", name=op.f("uq__bot_configs__token")),
        sa.UniqueConstraint("username", name=op.f("uq__bot_configs__username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_configs")
    # ### end Alembic commands ###
